# Generated by Django 4.1 on 2022-08-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=250)),
                ('limg', models.ImageField(upload_to='image2')),
                ('ltext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Languagesbg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lbimg', models.ImageField(upload_to='image3')),
            ],
        ),
        migrations.CreateModel(
            name='Programmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=250)),
                ('pimg', models.ImageField(upload_to='image1')),
                ('ptext', models.TextField()),
            ],
        ),
    ]
